const ShopActionType = {
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",
  // UPDATE_COLLECIONS: "UPDATE_COLLECIONS",
};

export default ShopActionType;
